Repository valory-xyz/trader-quickstart, pull requests merged in 2024-07, with the labels that each got.

#316 Release `v0.16.4`
  trades.py
Labels: release

#320 Bump the trader's version
  run_service.sh
Labels: bump

#321 Release `v0.16.5`
  run_service.sh
Labels: release

#322 Bump the trader to `v0.17.0`
  run_service.sh
Labels: bump

#324 Pin `cryptography` to avoid warnings from `paramiko`
  run_service.sh
Labels: chore

#327 Fix pinning
  run_service.sh
Labels: fix

#330 [v0.17.2]: Fix the policy update
  run_service.sh
Labels: fix

#328 Release `v0.17.2`
  run_service.sh
Labels: release

#329 Bump trader to `v0.18.0`
  run_service.sh
Labels: bump
